### ISSUE TITLE
Error in botcheck("barackobama") : could not find function "botcheck"

### ISSUE THREAD

**Issue by shipidhanorkar** [marsha5813/Botcheck#1]
I get an error that botcheck function was not found.

1) The install_github command was run successfully. 
**install_github("marsha5813/botcheck")**

> install_github("marsha5813/botcheck")
Downloading GitHub repo marsha5813/botcheck@master
from URL https://api.github.com/repos/marsha5813/botcheck/zipball/master
Installing botcheck
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/RJSONIO_1.3-0.tgz'
Content type 'application/x-gzip' length 1311082 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

Installing RJSONIO
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/8v/2rvm803s6gvdzdpdtkxn78s00000gn/T/RtmpADpbON/devtools2c3b7b12dcf2/RJSONIO'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *binary* package ‘RJSONIO’ ...
* DONE (RJSONIO)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/xml2_1.2.0.tgz'
Content type 'application/x-gzip' length 821238 bytes (801 KB)
==================================================
downloaded 801 KB

Installing xml2
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/Rcpp_0.12.16.tgz'
Content type 'application/x-gzip' length 4369705 bytes (4.2 MB)
==================================================
downloaded 4.2 MB

Installing Rcpp
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/8v/2rvm803s6gvdzdpdtkxn78s00000gn/T/RtmpADpbON/devtools2c3b778168a3/Rcpp'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *binary* package ‘Rcpp’ ...
* DONE (Rcpp)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/8v/2rvm803s6gvdzdpdtkxn78s00000gn/T/RtmpADpbON/devtools2c3bd6ca202/xml2'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *binary* package ‘xml2’ ...
* DONE (xml2)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/8v/2rvm803s6gvdzdpdtkxn78s00000gn/T/RtmpADpbON/devtools2c3b28bcad42/marsha5813-botcheck-0ed0082'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘botcheck’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (botcheck)

2) However, there was an error in loading xml2 with library command. 
> library(xml2)
Error in value[[3L]](cond) : 
  Package ‘xml2’ version 1.1.1 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘xml2’ is imported by ‘tidyverse’, ‘rvest’ so cannot be unloaded
In addition: Warning message:
package ‘xml2’ was built under R version 3.4.3

**Comment by shipidhanorkar** [comment]
Closing issue.  Tweaked a little bit and it worked.

**Comment by marsha5813** [comment]
Thanks for raising and closing the issue. Sorry I missed it. Can you let me know what you tweaked in case this problem comes up again?
