### ISSUE TITLE
Mashape Key

### ISSUE THREAD

**Issue by kurtawirth** [marsha5813/Botcheck#2]
I've signed up for Mashape but, once logged in, I can't seem to find my key. How would I generate/find this key? Sorry for the confusion!

**Comment by kurtawirth** [comment]
Just figured this out. 

- Create an application in "Overview" by clicking the dropdown menu.

- Then go to the application's page by clicking your profile in the top right of the screen.

- Then click "Get the keys" in the top right of the screen.

**Comment by marsha5813** [comment]
Thanks for this. I may add this information to a help file or maybe the readme at some point.

**Comment by kurtawirth** [comment]
Happy to help!
